site_name: Damian Gonzalez

nav:
  - Home: index.md
  - Perfil profesional:
    - Filosofía de ingeniería: perfil/filosofia-ingenieria.md
    - Principios técnicos: perfil/principios-tecnicos.md
    - Estilo de liderazgo: practicas/liderazgo.md
  - Practicas de ingeniería:
    - Ingeniería de requerimientos: practicas/toma-requerimientos.md
    - Definición e Ingeniería de Arquitectura: practicas/arquitectura.md
    - Planificación: practicas/planificacion.md
  - Estandares de calidad:
    - Gobernanza de Plataforma y Caminos Seguros: estandares/patrones-codigo.md
    - Arquitectura de Software y Patrones de Diseño: estandares/patrones-diseno.md
    - Ciclo de Vida de Calidad Automatizada: estandares/error-handler.md
  - Ingenieria de plataformas:
    - Develop Toolkit: herramientas/develop-toolkit.md
    - Transacctional framework: herramientas/transactional-framework.md
    - Async framework: herramientas/async-framework.md
    - Messaging platform: herramientas/messaging-platform.md
theme:
  name: readthedocs
  logo: img/picture.jpg
  favicon: img/logo.png
  language: es
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo oscuro
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo claro
  features:
    - navigation.instant
    - navigation.instant.prefetch

extra:
  favicon: img/logo.png