site_name: NeuroNexoTec

extra:
  favicon: img/logo.png

nav:
  - Home: ./comunidad/introduccion.md

theme: 
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
  locale: es
  features:
    - navigation.instant
    - navigation.instant.prefetch
repo_url: https://github.com/example/repository/

